/* eslint "global-require": "off" */

module.exports = {
    "add": require("./add"),
    "apply": require("./apply"),
    "at": require("./at"),
    "auto": require("./auto"),
    "bind": require("./bind"),
    "call": require("./call"),
    "contains": require("./contains"),
    "divide": require("./divide"),
    "each": require("./each"),
    "every": require("./every"),
    "expose": require("./expose"),
    "filter": require("./filter"),
    "find": require("./find"),
    "flip": require("./flip"),
    "free": require("./free"),
    "getter": require("./getter"),
    "has": require("./has"),
    "id": require("./id"),
    "join": require("./join"),
    "keys": require("./keys"),
    "loop": require("./loop"),
    "map": require("./map"),
    "mod": require("./mod"),
    "multiply": require("./multiply"),
    "not": require("./not"),
    "partial": require("./partial"),
    "picker": require("./picker"),
    "pipe": require("./pipe"),
    "compose": require("./compose"),
    "pluck": require("./pluck"),
    "privatize": require("./privatize"),
    "put": require("./put"),
    "putter": require("./putter"),
    "reduce": require("./reduce"),
    "repeat": require("./repeat"),
    "reverse": require("./reverse"),
    "setter": require("./setter"),
    "slice": require("./slice"),
    "some": require("./some"),
    "sort": require("./sort"),
    "split": require("./split"),
    "subtract": require("./subtract"),
    "toArray": require("./toArray"),
    "values": require("./values")
};
